import Head from "next/head";
import Image from "next/image";
// import styles from "../styles/Home.module.css";

// ? components import
import { Download, Features, SectionWrapper } from "../components";
// ? styles import
import { Box, Container, Typography } from "@mui/material";
// import index from "../styles/index.css";

// ? import assets
import assets from "../public/assets";

import { AssessmentTwoTone } from "@mui/icons-material";
import Fotter from "../components/Fotter";
export default function Home() {
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <SectionWrapper
          title="You own stores of Nifty NFTs. start Selling & Growing "
          description="Buy, Store, Collect NFTs, exchange & earn Crypto. Join 25+ million people using ProNef Marketplace"
          showBtn
          mockupImg={assets.homeHero}
          banner="banner"
        />
        <SectionWrapper
          title="Smart User Interface Marketplace"
          description="Experience a butery Ui of ProfNef NFT MarketPlace. Smooth Constant colors of a fluent Ui design "
          mockupImg={assets.homeCards}
          reverse
        />
        <Features />
        <SectionWrapper
          title="Deployment"
          description="OGApp is built using Expo which runs on all Users devices. You can easily get your app into peples hand. "
          reverse
          mockupImg={assets.feature}
        />
        <SectionWrapper
          title="Creative way to showcase the store"
          description="The app contains two screens. The first screen lists all NFTs while the second one shoes the details of the specifi NFT. "
          mockupImg={assets.mockup}
          banner="banner02"
        />

        <Download />
      </main>

      <Fotter />
    </Box>
  );
}
